### ISSUE TITLE
Get a warning in node-inspector browser console with Node.js 0.11.15

### ISSUE THREAD

**Issue by oliverzy** [node-inspector/node-inspector#535]
Hi,

When I debug an application with the latest Node.js 0.11.15, I got the following warning in the browser console:
`
Your Node version (undefined) has a partial support of profiler.
The stack frames tree doesn't show all stack frames due to low sampling rate.
The profiling data is incomplete and may show misleading results.
Update Node to 0.11.13 or newer to get full support.
`

Is it caused by V8 version upgrade in this release?
And another issue with  0.11.15 is once the node-inspector browser window is opened, the debugged script will automatically resume, but actually in the previous version, it will break in the first line that give you a chance to set breakpoint.

This behavior is correct when using 0.11.13 (0.11.14 is broken).

**Comment by amit-handa** [comment]
i cant debug the app using inspector. Same issue ... once browser window is opened, the debugged script resumes automatically!

**Comment by DaSpawn** [comment]
same message with 0.12

**Comment by reyx** [comment]
Same message in windows 7 with 0.12 from "chocolatey.org"

**Comment by radubrehar** [comment]
Same here with 0.12

**Comment by martinpinto** [comment]
same message here, using mac os x yosemite, node 0.12. Used to have same error on windows, but error disappeared once I restarted the computer.

**Comment by alirezaDavid** [comment]
+1

**Comment by domisa54** [comment]
same message on windows7 SP1 with Node v0.12.0 & Node Inspector v0.8.3
Your Node version (undefined) has a partial support of profiler.
The stack frames tree doesn't show all stack frames due to low sampling rate.
The profiling data is incomplete and may show misleading results.
Update Node to 0.11.13 or newer to get full support.
>> Error: Cannot find module 'C:\Program Files\nodejs\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.3.5\node-v14-win32-ia32\debug.node''

**Comment by brijrajsingh** [comment]
Same here on my ubuntu, I just upgraded my nodejs to latest stable, 
    "Your Node version (undefined) has a partial support of profiler.
The stack frames tree doesn't show all stack frames due to low sampling rate.
The profiling data is incomplete and may show misleading results.
Update Node to 0.11.13 or newer to get full support.
Error: Cannot find module '/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.3.5/node-v14-linux-x64/debug.node'"

**Comment by lebolo** [comment]
I get the same warning on Windows 7 SP1, Node.js 0.12.0 and Node Inspector v0.9.0.

**Comment by slang800** [comment]
I get the exact same output as @brijrajsingh

![image](https://cloud.githubusercontent.com/assets/1049204/6310805/7ee6b8f6-b928-11e4-8c9c-e8c030b1ab24.png)

**Comment by slang800** [comment]
...and downgrading to 0.11.13 doesn't seem to fix it:

![image](https://cloud.githubusercontent.com/assets/1049204/6311012/d22f1f60-b92a-11e4-84bf-c82f93188948.png)

**Comment by slang800** [comment]
Ok, removing node-inspector, reinstalling it (a couple times until the version number reported by `node-inspector --version` is `v0.9.0`... apparently something went wrong the first time), and restarting it got rid of the "Cannot find module..." part of the error. So now the only problem is the node version in the message says `undefined`.

**Comment by mrotaru** [comment]
Had exactly the same problem as in @slang80's screenshot. So I uninstalled node-inspector, cleared the cache and installed again. Now I don't get any warnings or errors.

However, the other problem still persists - not being able to debug the first time - but after setting breakpoints, and restarting it works perfectly.

**Comment by kuzroman** [comment]
Same problem, windows 7, node 0.12.0, node-inspector 0.9.1. 
Reinstall node-inspector & clear cache npm didn't problem.

**Comment by mikemaccana** [comment]
@mrotaru how did you clear the cache? Thanks!

**Comment by mrotaru** [comment]
@mikemaccana just `npm cache clean`

**Comment by mikemaccana** [comment]
Thanks @mrotaru

**Comment by briandela** [comment]
Also having this issue. As soon as you try to load the inspector in the browser the script resumes immediately. Makes it impossible to debug tests or program entry points.

Any known work arounds?

Versions:
node: 0.12.0
node-inspector: 0.9.1

**Comment by mrotaru** [comment]
@briandela since breakpoints are persisted across debugging sessions and the issue seems to be only with the initial (automatic) break, you can manually place a breakpoint at the start of the script on the first run, and then re-start node-inspector, and it sould break.

**Comment by Xiot** [comment]
I running into the same thing as well.
Windows 8
Node v0.12
Node Inspector v0.9.1

**Comment by bajtos** [comment]
> And another issue with 0.11.15 is once the node-inspector browser window is opened, the debugged script will automatically resume, but actually in the previous version, it will break in the first line that give you a chance to set breakpoint.

See #534 

> When I debug an application with the latest Node.js 0.11.15, I got the following warning in the browser console:
> ```
Your Node version (undefined) has a partial support of profiler. The stack frames tree doesn't show all stack frames due to low sampling rate. The profiling data is incomplete and may show misleading results. Update Node to 0.11.13 or newer to get full support. 
```

Can anybody reproduce this issue using the latest 0.9.x version of Node Inspector?

**Comment by Zysen** [comment]
@bajtos Yes i am still seeing this issue.
I have tried with node versions: 0.11.13, 0.11.16 and 0.12

$ node-debug --version
Node Inspector v0.9.1

$ node --version
v0.11.16

Javascript console output:
Your Node version (undefined) has a partial support of profiler.
The stack frames tree doesn't show all stack frames due to low sampling rate.
The profiling data is incomplete and may show misleading results.
Update Node to 0.11.13 or newer to get full support.

**Comment by 3y3** [comment]
@bajtos , this issue can be reproduced on machines with low and medium performance.
This is inconsistency of debugger's connection states.

If anybody want to fix this issue, look at `Debugger Client.is Connected` option.

**Comment by Zysen** [comment]
@3y3 @bajtos  I am also running this in a low resource environment.
25 MB of RAM for node, and not much CPU.

**Comment by digihaven** [comment]
Same here

Error:
Your Node version (undefined) has a partial support of profiler.
The stack frames tree doesn't show all stack frames due to low sampling rate.
The profiling data is incomplete and may show misleading results.
Update Node to 0.11.13 or newer to get full support.

ltd@ltd-FJ461AA-A2L-m8532f:~$ node-debug --version
Node Inspector v0.9.2
ltd@ltd-FJ461AA-A2L-m8532f:~$ node --version
v0.11.15

**Comment by segmentationfaulter** [comment]
same issue with node.js version 0.12.0

**Comment by poinsetty** [comment]
same issu with node.js version 0.12.1

**Comment by 3y3** [comment]
Fixed in #594.
You fill free to test it. Issue will be closed in 0.9.3 release.

**Comment by benbscholz** [comment]
When do you expect 0.9.3 to be released?

**Comment by dpwolfe** [comment]
Tested and the warning no longer appears with latest source.
OS X Yosemite 10.10.2
Node v0.12.0
Still not able to break into any source with this version of node, but that is a separate issue: https://github.com/node-inspector/node-inspector/issues/534

**Comment by kureus** [comment]
There appear to be two issues mentioned here. The version warning check everyone mentions, and the error loading a module that @brijrajsingh @slang800 @mrotaru mention, this seems to be the issue here https://github.com/node-inspector/node-inspector/issues/603. Do we have a known workaround or fix coming for this?

**Comment by 3y3** [comment]
Fixed in `0.10.0` release. Reopen this bug if the problem still persists for you.

**Comment by KrishnaPG** [comment]
Fresh installation of node-inspector today and getting the same below error:
![image](https://cloud.githubusercontent.com/assets/4610831/7568523/e8c13436-f820-11e4-894f-985bade7f723.png)

And the interesting part is: it is looking for "node-v11-win32-ia32", (32-bit) where as the machine is 64-bit and I can see folder with name "node-v14-win32-x64"

**Comment by 3y3** [comment]
@KrishnaPG , move to #631, and look at discussion. I wonder to see information about your 
```
> npm version
```

**Comment by KrishnaPG** [comment]
Thanks @3y3 . Will follow #631 . Meanwhile, here is my npm version output:
````
{ npm: '2.7.4',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.2',
  openssl: '1.0.1m',
  uv: '1.4.2-node1',
  v8: '3.28.73',
  zlib: '1.2.8' }
````
Its 64 bit Windows.

**Comment by 3y3** [comment]
@KrishnaPG , what about debugged process? Is it possible that it uses other version of node?

**Comment by KrishnaPG** [comment]
It is a meteor project I was trying to debug (started with node debug options). It started on port 5858 and shows something like below:
````
Type: connect
V8-Version: 3.14.5.9
Protocol-Version: 1
Embedding-Host: node v0.10.36
Content-Length: 0
````
And the output of node-inspector -v is: `Node Inspector v0.10.0`

**Comment by 3y3** [comment]
Nice! You need to take a recipe what described in #631. So you need to use `npm install -g node-inspector --target=0.11.13`.
Replace 0.11.13 on node version used in meteor.
Keep in mind what after this step you'll need to reinstall node-inspactor for debugging `0.12` node scripts.

This is a workaround.

**Comment by KrishnaPG** [comment]
Thank you @3y3 It is almost close. With the target option, I can see "node-v11-win32-x64" directory built successfully but still the "node-v11-win32-ia32" directory missing (32-bit version).

So, the node-inspector still complained with same error. Is it possible to also specify the target platform option for `npm install` something like `npm install --platform=ia32 --target=`

I manually built the ia32 version from Visual Studio and put it in that directory. Then it complained about some missing function
![image](https://cloud.githubusercontent.com/assets/4610831/7578040/feee40e0-f86c-11e4-8067-2a1d90a0ffe1.png)

**Comment by 3y3** [comment]
@KrishnaPG , `--target_arch=ia32`. For other options look at `node-pre-gyp` project.

**Comment by ddimitrov90** [comment]
Any idea why i get  "Error: Cannot find module '/usr/lib/node_modules/node-inspector/lib/InjectorServer.js'"? 
I have upgraded to latest node-inspector - 0.10.2 and my node version is 0.10.33 :(

**Comment by sudeepdk** [comment]
My file is loading on below port but not able to start debug / hit break point 
http://localhost:8080/?ws=localhost:8080&port=5858

and my App is running @ http://localhost:5001/

IN console getting "No frames"  Error
