### ISSUE TITLE
hidden doesn't work

### ISSUE THREAD

**Issue by zwhitchcox** [node-inspector/node-inspector#544]
I have two files
```test.js``` :
```js
require('./test2')()
console.log('hello')
```
and ```test2.js``` :
```js
module.exports = function(){console.log('hello')}
```

To my understanding, when I type
```sh
node-debug test.js --hidden test2
```

it should not show any of the code excuted in ```test2.js``` in the debugger, but it does.

Am I missing something?

**Comment by 3y3** [comment]
Please submit that this issue fixed in 0.9.0

**Comment by bajtos** [comment]
Closing this issue as fixed, feel free to reopen if you can reproduce the problem using the latest version of Node Inspector.

**Comment by nmccready** [comment]
Can you reference the commit that resolved this? I am still seeing issues using the rc file.

**Comment by zacronos** [comment]
@3y3, @bajtos, I can confirm this issue exists using 0.9.2.  Do you want to reopen this issue, or should I create a new issue?

I am currently using node v0.10.32.  I created test.js and test2.js as below for an easier test:

test.js
-------
```
var test2 = require('./test2');
console.log('hello 1');
test2();
```

test2.js
---------
```
module.exports = function() {
  console.log('hello 2');
}
```

Then I run `node-debug test.js --hidden 'test2'`.  The debugger loads with script execution paused, I switch to test2.js, add a breakpoint on the console.log line, resume execution, and the debugger breaks on my breakpoint in test2.js, even though that file should be ignored because of `--hidden`.

**Comment by bajtos** [comment]
@zacronos Can you reproduce the problem on 0.7.x version too? What is your platform?

**Comment by zacronos** [comment]
@bajtos, I see the same behavior on 0.7.4 of node-inspector.

I am using node v0.10.32 on OS X 10.9.5 with Chrome 41.0.2272.89 (64-bit).  If there is any other information you'd like or scenarios you'd like me to test, let me know.

Thanks for the fast response!

**Comment by 3y3** [comment]
@zacronos , you start debugger with wrong command line:
your - `node-debug test.js --hidden 'test2'`
expected - `node-debug --hidden 'test2' test.js`

With correct commant line I can't reproduce your issue.

**Comment by 3y3** [comment]
@zwhitchcox , same as @zacronos 

I close this issue. You feel free to reopen it if I'm wrong here.
