### ISSUE TITLE
Pre-built binaries not found for v8-debug@0.7.7 and node@7.1.0

### ISSUE THREAD

**Issue by ezzaouia** [node-inspector/node-inspector#950]
- Command:
   npm i -g git+https://github.com/node-inspector/node-inspector.git

- Logs :
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.1.0 (node-v51 ABI) (falling back to source compile with node-gyp)

- Env :
✗ node --version
v7.1.0
✗ npm --version
3.10.9

**Comment by DealPete** [comment]
I'm having the same problem. And when it falls back to compiling, I get these errors:
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:38:27: error: too few arguments to function call, expected at least 2,
      have 1
        v8::Debug::Call(fn);
        ~~~~~~~~~~~~~~~   ^
/Users/dealpete/.node-gyp/7.1.0/include/node/v8-debug.h:198:3: note: 'Call' declared here
  static MaybeLocal<Value> Call(Local<Context> context,
  ^
../src/debug.cc:46:61: error: too few arguments to function call, single argument
      'isolate' was not specified
        Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate();
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/dealpete/.node-gyp/7.1.0/include/node/v8-debug.h:248:3: note: 'GetDebugContext'
      declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:61:67: error: too few arguments to function call, single argument
      'isolate' was not specified
        Local<Context> debug_context = v8::Debug::GetDebugContext();
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/dealpete/.node-gyp/7.1.0/include/node/v8-debug.h:248:3: note: 'GetDebugContext'
      declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
../src/debug.cc:66:54: error: too few arguments to function call, single argument
      'isolate' was not specified
          debug_context = v8::Debug::GetDebugContext();
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/dealpete/.node-gyp/7.1.0/include/node/v8-debug.h:248:3: note: 'GetDebugContext'
      declared here
  static Local<Context> GetDebugContext(Isolate* isolate);
  ^
4 errors generated.
make: *** [Release/obj.target/debug/src/debug.o] Error 1

**Comment by black-snow** [comment]
Error on Win10 x64, node 7.0.0

`$ npm install -g node-inspector`

> v8-debug@0.7.7 preinstall C:\Users\xxx\AppData\Roaming\npm\node_modules\.staging\v8-debug-ab58e119
> node -e 'process.exit(0)'


> v8-profiler@5.6.5 preinstall C:\Users\xxx\AppData\Roaming\npm\node_modules\.staging\v8-profiler-f7edcbfd
> node -e 'process.exit(0)'

> C:\Users\xxx\AppData\Roaming\npm\node-inspector -> C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\bin\inspector.js
C:\Users\xxx\AppData\Roaming\npm\node-debug -> C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\bin\node-debug.js

> v8-debug@0.7.7 install C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

> node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.0.0 (node-v51 ABI) (falling back to source compile with node-gyp)

> C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

> C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64\debug.node --module_name=debug --module_path=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64 )  else (node "" configure --fallback-to-build --module=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64\debug.node --module_name=debug --module_path=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64 )

> C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64\debug.node --module_name=debug --module_path=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64 )  else (node "" build --fallback-to-build --module=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64\debug.node --module_name=debug --module_path=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64 )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm▒glichen, m▒ssen Sie den Schalter "/m" hinzuf▒gen.
  debug.cc
  InjectedScriptHost.cc
  win_delay_load_hook.cc
..\src\debug.cc(38): error C2660: "v8::Debug::Call": Funktion akzeptiert keine 1 Argumente [C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug.vcxproj]
..\src\debug.cc(46): error C2660: "v8::Debug::GetDebugContext": Funktion akzeptiert keine 0 Argumente..\src\InjectedScriptHost.cc(173): warning C4996: 'v8::Object::GetRealNamedProperty': wurde als veraltet deklariert [C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug.vcxproj]

>  c:\users\xxx\.node-gyp\7.0.0\include\node\v8.h(2949): note: Siehe Deklaration von "v8::Object::GetRealNamedProperty"
..\src\debug.cc(46): error C2227: Links von "->GetIsolate" muss sich ein Zeiger auf Klassen-/Struktur-/Union-/generischen Typ befinden. [C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug.vcxproj]
..\src\debug.cc(61): error C2660: "v8::Debug::GetDebugContext": Funktion akzeptiert keine 0 Argumente [C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug.vcxproj]
..\src\debug.cc(66): error C2660: "v8::Debug::GetDebugContext": Funktion akzeptiert keine 0 Argumente [C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v0.7.7\\node-v51-win32-x64\\debug.node" "--module_name=debug" "--module_path=C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v0.7.7\\node-v51-win32-x64"
gyp ERR! cwd C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64\debug.node --module_name=debug --module_path=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug
node-pre-gyp ERR! node -v v7.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64\debug.node --module_name=debug --module_path=C:\Users\xxx\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64' (1)
C:\Users\xxx\AppData\Roaming\npm
`-- (empty)

> npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-inspector"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

> npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

**Comment by virtualadrian** [comment]
This isn't the ideal solution, but I downgraded to 6.9.1 and things are back to normal. I didn't need anything specific from 7.x, so that was ok in my instance.  

[https://nodejs.org/en/download/package-manager/](https://nodejs.org/en/download/package-manager/)

**Comment by CharlieUofT** [comment]
Same issue, downgrade makes everything fine

**Comment by msholty-fd** [comment]
@virtualadrian This worked for me. I am using nvm and ran `nvm install 6.9.1` and then `nvm use 6.9.1` and it installed just fine. Thank you.

**Comment by lostcodder** [comment]
@virtualadrian it installed just fine but it just not works

**Comment by clayzermk1** [comment]
:+1: seeing this as well.
Linux Mint 18
node 7.2.1
npm 4.0.3

**Comment by dobryanskyy** [comment]
I also see this on 
windows 7
node 7.2.1
npm 3.10.10

**Comment by stevenxxiu** [comment]
:+1:

**Comment by sumant30** [comment]
Yep downgrading to ver 6.9.5 worked for me.

**Comment by sandro-pasquali** [comment]
Won't install on Node 7.5.0 (npm 4.1.2, OSX 10.10.5). 

Same issues/output as @DealPete 

Unfortunately downgrading is not an option for me.

**Comment by simonvomeyser** [comment]
Having the same problem - same specs as sandro-pasquali.

Downgrading to 6.9.5 does work for me too but I hope this will be fixed soon. 

Keep up the good work and thank you!

**Comment by javierbq** [comment]
same problem.

**Comment by shockey** [comment]
Same problem here.

**Comment by Sasha-Sh** [comment]
Same problem on:
OSX: 10.10 
Node: v7.7.1
npm: 2.15.1

**Comment by mitsuhisaT** [comment]
Same problem on
MINGW64_NT-6.1(MS-Windows 7 64bit)
Node v7.5.0
npm 4.0.5

**Comment by arssonist** [comment]
oSX 10.11
Node- 7.7.0

ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz

Then I get this:
`code-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

This is followed by a long error log.

**Comment by jimmyko** [comment]
@virtualadrian 's solution work for me.

**Comment by BayoAdejare** [comment]
Same problem on:
Windows 10 (x64)
Node v7.7.1
npm 4.1.2

**Comment by CharlyCheng** [comment]
Same problem on:
OSX: 10.10
Node: v7.6.0
npm: 4.1.2

**Comment by lf94** [comment]
Just ran into this today as well.

Debian Jessie
NodeJS 7.5.0
npm 4.1.2

**Comment by CharlyCheng** [comment]
Ok,I will try !






At 2017-03-24 22:21:28, "Lee" <notifications@github.com> wrote:


Just ran into this today as well.

Debian Jessie
NodeJS 7.5.0
npm 4.1.2

**Comment by hustxiaoc** [comment]
The issue has been resolved, try `node-inspector@1.0.0` please!

**Comment by Dutchboy** [comment]
@hustxiaoc  The issue has NOT solved.

**Comment by Dutchboy** [comment]
It is obvious, node-inspector (1.0.0) still cannot be run with node 7.5.0 (versions 7?) so, install nvm https://github.com/creationix/nvm

**Comment by hustxiaoc** [comment]
```
➜  test npm i -g git+https://github.com/node-inspector/node-inspector.git

> v8-debug@1.0.1 preinstall /Users/taojie/.nvm/versions/node/v7.8.0/lib/node_modules/.staging/v8-debug-b05911c2
> node -e 'process.exit(0)'


> v8-profiler@5.7.0 preinstall /Users/taojie/.nvm/versions/node/v7.8.0/lib/node_modules/.staging/v8-profiler-d9d1fe5d
> node -e 'process.exit(0)'

/Users/taojie/.nvm/versions/node/v7.8.0/bin/node-debug -> /Users/taojie/.nvm/versions/node/v7.8.0/lib/node_modules/node-inspector/bin/node-debug.js
/Users/taojie/.nvm/versions/node/v7.8.0/bin/node-inspector -> /Users/taojie/.nvm/versions/node/v7.8.0/lib/node_modules/node-inspector/bin/inspector.js

> v8-debug@1.0.1 install /Users/taojie/.nvm/versions/node/v7.8.0/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

[v8-debug] Success: "/Users/taojie/.nvm/versions/node/v7.8.0/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v51-darwin-x64/debug.node" is installed via remote

> v8-profiler@5.7.0 install /Users/taojie/.nvm/versions/node/v7.8.0/lib/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

[v8-profiler] Success: "/Users/taojie/.nvm/versions/node/v7.8.0/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.7.0/node-v51-darwin-x64/profiler.node" is installed via remote
/Users/taojie/.nvm/versions/node/v7.8.0/lib
└─┬ node-inspector@1.0.0  (git+https://github.com/node-inspector/node-inspector.git#bc09cc0e91cd6de9b2c72d3169955a5118d5dfb9)
  ├── async@0.9.2
  ├─┬ biased-opener@0.2.8
  │ ├─┬ browser-launcher2@0.4.6
  │ │ ├── headless@0.1.7
  │ │ ├── lodash@2.4.2
  │ │ ├─┬ mkdirp@0.5.1
  │ │ │ └── minimist@0.0.8
  │ │ ├─┬ osenv@0.1.4
  │ │ │ ├── os-homedir@1.0.2
  │ │ │ └── os-tmpdir@1.0.2
  │ │ ├─┬ plist@1.2.0
  │ │ │ ├── base64-js@0.0.8
  │ │ │ ├── util-deprecate@1.0.2
  │ │ │ ├─┬ xmlbuilder@4.0.0
  │ │ │ │ └── lodash@3.10.1
  │ │ │ └── xmldom@0.1.27
  │ │ ├── rimraf@2.2.8
  │ │ ├── uid@0.0.2
  │ │ └─┬ win-detect-browsers@1.0.2
  │ │   ├── after@0.8.2
  │ │   ├── xtend@4.0.1
  │ │   └── yargs@1.3.3
  │ ├── minimist@1.2.0
  │ └─┬ x-default-browser@0.3.1
  │   └─┬ default-browser-id@1.0.4
  │     ├─┬ bplist-parser@0.1.1
  │     │ └── big-integer@1.6.17
  │     ├─┬ meow@3.7.0
  │     │ ├── camelcase-keys@2.1.0
  │     │ ├─┬ loud-rejection@1.6.0
  │     │ │ └─┬ currently-unhandled@0.4.1
  │     │ │   └── array-find-index@1.0.2
  │     │ ├── map-obj@1.0.1
  │     │ ├─┬ normalize-package-data@2.3.6
  │     │ │ ├── hosted-git-info@2.4.1
  │     │ │ ├─┬ is-builtin-module@1.0.0
  │     │ │ │ └── builtin-modules@1.1.1
  │     │ │ └─┬ validate-npm-package-license@3.0.1
  │     │ │   ├─┬ spdx-correct@1.0.2
  │     │ │   │ └── spdx-license-ids@1.2.2
  │     │ │   └── spdx-expression-parse@1.0.4
  │     │ ├── object-assign@4.1.1
  │     │ ├─┬ read-pkg-up@1.0.1
  │     │ │ ├─┬ find-up@1.1.2
  │     │ │ │ ├── path-exists@2.1.0
  │     │ │ │ └─┬ pinkie-promise@2.0.1
  │     │ │ │   └── pinkie@2.0.4
  │     │ │ └─┬ read-pkg@1.1.0
  │     │ │   ├─┬ load-json-file@1.1.0
  │     │ │   │ ├─┬ parse-json@2.2.0
  │     │ │   │ │ └─┬ error-ex@1.3.1
  │     │ │   │ │   └── is-arrayish@0.2.1
  │     │ │   │ ├── pify@2.3.0
  │     │ │   │ └─┬ strip-bom@2.0.0
  │     │ │   │   └── is-utf8@0.2.1
  │     │ │   └── path-type@1.1.0
  │     │ ├─┬ redent@1.0.0
  │     │ │ ├─┬ indent-string@2.1.0
  │     │ │ │ └─┬ repeating@2.0.1
  │     │ │ │   └── is-finite@1.0.2
  │     │ │ └─┬ strip-indent@1.0.1
  │     │ │   └── get-stdin@4.0.1
  │     │ └── trim-newlines@1.0.0
  │     └── untildify@2.1.0
  ├─┬ debug@2.6.3
  │ └── ms@0.7.2
  ├─┬ express@4.15.2
  │ ├─┬ accepts@1.3.3
  │ │ ├─┬ mime-types@2.1.15
  │ │ │ └── mime-db@1.27.0
  │ │ └── negotiator@0.6.1
  │ ├── array-flatten@1.1.1
  │ ├── content-disposition@0.5.2
  │ ├── content-type@1.0.2
  │ ├── cookie@0.3.1
  │ ├── cookie-signature@1.0.6
  │ ├── debug@2.6.1
  │ ├── depd@1.1.0
  │ ├── encodeurl@1.0.1
  │ ├── escape-html@1.0.3
  │ ├── etag@1.8.0
  │ ├─┬ finalhandler@1.0.1
  │ │ └── unpipe@1.0.0
  │ ├── fresh@0.5.0
  │ ├── merge-descriptors@1.0.1
  │ ├── methods@1.1.2
  │ ├─┬ on-finished@2.3.0
  │ │ └── ee-first@1.1.1
  │ ├── parseurl@1.3.1
  │ ├── path-to-regexp@0.1.7
  │ ├─┬ proxy-addr@1.1.4
  │ │ ├── forwarded@0.1.0
  │ │ └── ipaddr.js@1.3.0
  │ ├── qs@6.4.0
  │ ├── range-parser@1.2.0
  │ ├─┬ send@0.15.1
  │ │ ├── debug@2.6.1
  │ │ ├── destroy@1.0.4
  │ │ ├── http-errors@1.6.1
  │ │ └── mime@1.3.4
  │ ├── serve-static@1.12.1
  │ ├── setprototypeof@1.0.3
  │ ├── statuses@1.3.1
  │ ├─┬ type-is@1.6.14
  │ │ └── media-typer@0.3.0
  │ ├── utils-merge@1.0.0
  │ └── vary@1.1.1
  ├─┬ glob@5.0.15
  │ ├─┬ inflight@1.0.6
  │ │ └── wrappy@1.0.2
  │ ├── inherits@2.0.3
  │ ├─┬ minimatch@3.0.3
  │ │ └─┬ brace-expansion@1.1.6
  │ │   ├── balanced-match@0.4.2
  │ │   └── concat-map@0.0.1
  │ └── once@1.4.0
  ├── path-is-absolute@1.0.1
  ├─┬ rc@1.2.0
  │ ├── deep-extend@0.4.1
  │ ├── ini@1.3.4
  │ └── strip-json-comments@2.0.1
  ├── semver@4.3.6
  ├─┬ serve-favicon@2.4.2
  │ └── ms@1.0.0
  ├─┬ strong-data-uri@1.0.4
  │ └── truncate@1.0.5
  ├─┬ v8-debug@1.0.1
  │ ├── nan@2.5.1
  │ └─┬ node-pre-gyp@0.6.34
  │   ├─┬ nopt@4.0.1
  │   │ └── abbrev@1.1.0
  │   ├─┬ npmlog@4.0.2
  │   │ ├─┬ are-we-there-yet@1.1.2
  │   │ │ └── delegates@1.0.0
  │   │ ├── console-control-strings@1.1.0
  │   │ ├─┬ gauge@2.7.3
  │   │ │ ├── aproba@1.1.1
  │   │ │ ├── has-unicode@2.0.1
  │   │ │ ├── signal-exit@3.0.2
  │   │ │ └── wide-align@1.1.0
  │   │ └── set-blocking@2.0.0
  │   ├─┬ request@2.81.0
  │   │ ├── aws-sign2@0.6.0
  │   │ ├── aws4@1.6.0
  │   │ ├── caseless@0.12.0
  │   │ ├─┬ combined-stream@1.0.5
  │   │ │ └── delayed-stream@1.0.0
  │   │ ├── extend@3.0.0
  │   │ ├── forever-agent@0.6.1
  │   │ ├─┬ form-data@2.1.2
  │   │ │ └── asynckit@0.4.0
  │   │ ├─┬ har-validator@4.2.1
  │   │ │ ├─┬ ajv@4.11.5
  │   │ │ │ ├── co@4.6.0
  │   │ │ │ └─┬ json-stable-stringify@1.0.1
  │   │ │ │   └── jsonify@0.0.0
  │   │ │ └── har-schema@1.0.5
  │   │ ├─┬ hawk@3.1.3
  │   │ │ ├── boom@2.10.1
  │   │ │ ├── cryptiles@2.0.5
  │   │ │ ├── hoek@2.16.3
  │   │ │ └── sntp@1.0.9
  │   │ ├─┬ http-signature@1.1.1
  │   │ │ ├── assert-plus@0.2.0
  │   │ │ ├─┬ jsprim@1.4.0
  │   │ │ │ ├── assert-plus@1.0.0
  │   │ │ │ ├── extsprintf@1.0.2
  │   │ │ │ ├── json-schema@0.2.3
  │   │ │ │ └── verror@1.3.6
  │   │ │ └─┬ sshpk@1.11.0
  │   │ │   ├── asn1@0.2.3
  │   │ │   ├── assert-plus@1.0.0
  │   │ │   ├── bcrypt-pbkdf@1.0.1
  │   │ │   ├─┬ dashdash@1.14.1
  │   │ │   │ └── assert-plus@1.0.0
  │   │ │   ├── ecc-jsbn@0.1.1
  │   │ │   ├─┬ getpass@0.1.6
  │   │ │   │ └── assert-plus@1.0.0
  │   │ │   ├── jodid25519@1.0.2
  │   │ │   ├── jsbn@0.1.1
  │   │ │   └── tweetnacl@0.14.5
  │   │ ├── is-typedarray@1.0.0
  │   │ ├── isstream@0.1.2
  │   │ ├── json-stringify-safe@5.0.1
  │   │ ├── oauth-sign@0.8.2
  │   │ ├── performance-now@0.2.0
  │   │ ├── safe-buffer@5.0.1
  │   │ ├── stringstream@0.0.5
  │   │ ├─┬ tough-cookie@2.3.2
  │   │ │ └── punycode@1.4.1
  │   │ ├── tunnel-agent@0.6.0
  │   │ └── uuid@3.0.1
  │   ├─┬ rimraf@2.6.1
  │   │ └─┬ glob@7.1.1
  │   │   └── fs.realpath@1.0.0
  │   ├── semver@5.3.0
  │   ├─┬ tar@2.2.1
  │   │ ├── block-stream@0.0.9
  │   │ └─┬ fstream@1.0.11
  │   │   └── graceful-fs@4.1.11
  │   └─┬ tar-pack@3.4.0
  │     ├── fstream-ignore@1.0.5
  │     ├─┬ readable-stream@2.2.6
  │     │ ├── buffer-shims@1.0.0
  │     │ ├── core-util-is@1.0.2
  │     │ ├── isarray@1.0.0
  │     │ ├── process-nextick-args@1.0.7
  │     │ └── string_decoder@0.10.31
  │     ├─┬ rimraf@2.6.1
  │     │ └── glob@7.1.1
  │     └── uid-number@0.0.6
  ├── v8-profiler@5.7.0
  ├─┬ which@1.2.14
  │ └── isexe@2.0.0
  ├─┬ ws@1.1.4
  │ ├── options@0.0.6
  │ └── ultron@1.0.2
  └─┬ yargs@3.32.0
    ├── camelcase@2.1.1
    ├─┬ cliui@3.2.0
    │ ├─┬ strip-ansi@3.0.1
    │ │ └── ansi-regex@2.1.1
    │ └── wrap-ansi@2.1.0
    ├── decamelize@1.2.0
    ├─┬ os-locale@1.4.0
    │ └─┬ lcid@1.0.0
    │   └── invert-kv@1.0.0
    ├─┬ string-width@1.0.2
    │ ├── code-point-at@1.1.0
    │ └─┬ is-fullwidth-code-point@1.0.0
    │   └── number-is-nan@1.0.1
    ├── window-size@0.1.4
    └── y18n@3.2.1

➜  test node-inspector -v
Node Inspector v1.0.0
```

**Comment by SILVERjl** [comment]
+1 - I also can not run node 7.7.3 for this issue.  And I need 7+ for await so downgrade is not an option either :(

**Comment by grath10** [comment]
same problem

**Comment by qiangzi7723** [comment]
same problem and I don't want to downgraded my node version

**Comment by barocsi** [comment]
same
cant believe its happening each time I mess with node-gyp

**Comment by shivarajnaidu** [comment]
I am using Nodejs v8.5.0 and npm 5.3.0.. Same Issue :cry:

**Comment by weeco** [comment]
Same issue here, running Node 8.2.1 and npm 5.3.0

**Comment by lalitkapoor** [comment]
same with node v8.7.0 and npm v5.5.1 and yarn v0.20.3

**Comment by chen199** [comment]
Same issue with node v8.6.0 and npm v5.3.0. Ridiculous.

**Comment by Fotiman** [comment]
Still present with node v8.9.0 (LTS) and npm 5.5.1

**Comment by hustxiaoc** [comment]
Hey guys, I'm sorry that Node-Inspector doesn't work on Node8.x

**Comment by CodingBo** [comment]
Still present with node v8.9.3 and npm 5.5.1

PS G:\gitRepo\vux-pro> npm install vuex --save

> node-zopfli@2.0.2 install G:\gitRepo\vux-pro\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.2 and node@8.9.3 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)

G:\gitRepo\vux-pro\node_modules\node-zopfli>if not defined npm_config_node_gyp (node "E:\Node.js\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

G:\gitRepo\vux-pro\node_modules\node-zopfli>if not defined npm_config_node_gyp (node "E:\Node.js\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=G:\gitRepo\vux-pro\node_modules\node-zopfli\lib\binding\node-v57-win32-x64\zopfli.node --module_name=zopfli --module_path=G:\gitRepo\vux-pro\node_modules\node-zopfli\lib\binding\node-v57-win32-x64 )  else (node "" configure --fallback-to-build --module=G:\gitRepo\vux-pro\node_modules\node-zopfli\lib\binding\node-v57-win32-x64\zopfli.node --module_name=zopfli --module_path=G:\gitRepo\vux-pro\node_modules\node-zopfli\lib\binding\node-v57-win32-x64 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (E:\Node.js\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (E:\Node.js\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at E:\Node.js\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "E:\\Node.js\\node.exe" "E:\\Node.js\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=G:\\gitRepo\\vux-pro\\node_modules\\node-zopfli\\lib\\binding\\node-v57-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=G:\\gitRepo\\vux-pro\\node_modules\\node-zopfli\\lib\\binding\\node-v57-win32-x64"
gyp ERR! cwd G:\gitRepo\vux-pro\node_modules\node-zopfli
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=G:\gitRepo\vux-pro\node_modules\node-zopfli\lib\binding\node-v57-win32-x64\zopfli.node --module_name=zopfli --module_path=G:\gitRepo\vux-pro\node_modules\node-zopfli\lib\binding\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (G:\gitRepo\vux-pro\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "E:\\Node.js\\node.exe" "G:\\gitRepo\\vux-pro\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd G:\gitRepo\vux-pro\node_modules\node-zopfli
node-pre-gyp ERR! node -v v8.9.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=G:\gitRepo\vux-pro\node_modules\node-zopfli\lib\binding\node-v57-win32-x64\zopfli.node --module_name=zopfli --module_path=G:\gitRepo\vux-pro\node_modules\node-zopfli\lib\binding\node-v57-win32-x64' (1)
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@2.0.2 (node_modules\node-zopfli):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@2.0.2 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ vuex@2.5.0
added 139 packages and updated 1 package in 90.05s

**Comment by marcelo-hexsel** [comment]
Same error with npm 5.6.0 and node v8.9.4 in linux environment (ubuntu)

**Comment by learner-long-life** [comment]
Same error with npm 5.7.1 and node 9.7.1 on Mac OSX 10.12.6

**Comment by e-monson** [comment]
Gotta love those 3-year-old open issues on commonly used and recommended tools.

**Comment by AlexanderMer** [comment]
Same issue with Node 12 (LTS)
